services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfiles/app/Dockerfile
    container_name: app
    ports:
      - "${APP_PORT:-8000}:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - dm-network

  db:
    build: ./Dockerfiles/postgres
    container_name: db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-dm}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - dm-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  dm-network:
    driver: bridge
